spring:
  datasource:
    url: jdbc:mysql://localhost:3306/devdb
    username: team1
    password: passwordHere
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
